AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a VPC, with a public subnet. It deploys an Internet Gateway, with a default route on the public subnet. It deploys an EC2 instance in the public subnet to serve as a bastion host"

Parameters:
  EnvironmentName:
    Description: Provide a environment name that will be added to prefix to resource names
    Type: String
    Default: N/W Workshop
  VPC_CIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    AllowedPattern: ((\\d{1,3})\\.){3}\\d{1,3}/\\d{1,2}
    Default: 10.0.0.0/16

Resources:
  # Non-Prod 1 Resources
  VPC:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    Properties:
      TemplateURL: https://cf-templates-19uicow2on7s5-ap-south-1.s3.ap-south-1.amazonaws.com/rds-parameter-child1