AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a VPC, with a public subnet. It deploys an Internet Gateway, with a default route on the public subnet. It deploys an EC2 instance in the public subnet to serve as a bastion host"

Resources:
  # Non-Prod 1 Resources
  VPC:
    Type: AWS::EC2::VPC
      Properties:
        CidrBlock:
          Ref: VpcCIDR
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value:
               Ref: EnvironmentName