AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a VPC, with a public subnet. It deploys an Internet Gateway, with a default route on the public subnet. It deploys an EC2 instance in the public subnet to serve as a bastion host"
Parameters:
  ChildSubnetCIDR:
    Description: Subnet_CIDR
    Type: String
  VPC:
    Description: VPC_ID
    Type: String
Resources:
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      #AvailabilityZone: !Select [0, !GetAZs AWS::Region]
      CidrBlock: !Ref ChildSubnetCIDR
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
