AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a VPC, with a public subnet. It deploys an Internet Gateway, with a default route on the public subnet. It deploys an EC2 instance in the public subnet to serve as a bastion host"
Parameters:
  ChildSubnetCIDR:
    Description: Subnet_CIDR
    Type: String
  VPC:
    Description: VPC_ID
    Type: String
  InstanceSecurityGroup:
    Description: Security Grp for EC2 Instances
    Type: String
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Ref ChildSubnetCIDR
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
  EC2Instance:
      DependsOn: PrivateSubnet
      Type: AWS::EC2::Instance
      Properties:
        ImageId: !Ref LatestAmiId
        InstanceType: t2.micro
        NetworkInterfaces:
          - AssociatePublicIpAddress: false
            DeviceIndex: '0'
            DeleteOnTermination: true
            SubnetId: !Ref PrivateSubnet
            GroupSet:
              - !Ref InstanceSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            # install updates
            /bin/sudo su
            yum update -y
            # configure password based logon via SSH
            sudo su
            /bin/echo 'pa55w0rd' | /bin/passwd ec2-user --stdin
            sed -i  '/PasswordAuthentication/d' /etc/ssh/sshd_config
            sed -i  '/PermitRootLogin/d' /etc/ssh/sshd_config
            echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
            echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
            systemctl restart sshd
            #
        Tags:
          - Key: Name
            Value: Private Host