AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a VPC, with a public subnet. It deploys an Internet Gateway, with a default route on the public subnet. It deploys an EC2 instance in the public subnet to serve as a bastion host"

Parameters:
  EnvironmentName:
    Description: Provide a environment name that will be added to prefix to resource names
    Type: String
    Default: NetowrkingWorkshop
  RegionCIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: Please enter the IP range (CIDR notation) for this Region
    Type: String
    Default: 10.0.0.0/16
  CloudFormationS3Bucket:
    Description: Specify S3 Bucket name
    Type: String
Resources:
  VPC0:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Join
          - ''
          - - 'https://'
            - !Ref CloudFormationS3Bucket
            - '.s3.us-east-1.amazonaws.com/nw-workshop-vpc.yml'
      Parameters:
        ChildVPCCIDR: !Select [ 0, !Cidr [ !Ref  RegionCIDR, 2, 14 ]]
        CloudFormationS3Bucket : !Ref CloudFormationS3Bucket
  VPC1:
    Type: AWS::CloudFormation::Stack
    Properties:
     TemplateURL:
        !Join
          - ''
          - - 'https://'
            - !Ref CloudFormationS3Bucket
            - '.s3.us-east-1.amazonaws.com/nw-workshop-vpc.yml'
     Parameters:
        ChildVPCCIDR: !Select [ 1, !Cidr [ !Ref  RegionCIDR, 2, 14 ]]
        CloudFormationS3Bucket : !Ref CloudFormationS3Bucket
